### ISSUE TITLE
Stop using `which`

### ISSUE THREAD

**Issue by dimo414** [dimo414/ProfileGem#25]
http://mywiki.wooledge.org/BashFAQ/081

```
$ grep which -R . --exclude=LICENSE --exclude=README.md
```

**Comment by jon-butler** [comment]
"command -v" does not appear to work as intended for me:

$ bash --version | grep bash
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
$ command -v bat
bat
$ echo $?
0

Dropping the -v does seem to work as intended, but prints an error message.

$ command bat
-bash: bat: command not found
$ echo $?
127

How about "command bat 2>/dev/null"?

**Comment by dimo414** [comment]
The `-v` triggers different behavior, see [`man bash`](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html#index-command). Specifically:

`command -v bat` succeeds because it found a shell function named `bat` (try `command -V bat` or `type -t bat` to see this). By contrast (and somewhat confusingly) `command bat` invokes `bat` "ignoring any shell function named [`bat`]."

The reason `command -v bat` succeeds is because [`pg::require`](https://github.com/dimo414/ProfileGem/blob/fed2ea8/utilityFunctions.sh#L172) introduces such a function to aid discovery.

Alas, as I assume you're running into, that makes `command -v` not the right check in `prompt.gem/environment.sh`. I'll submit a fix shortly; the right command to do this check is [`type -P`](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html#index-type).

(it's also possible you're sourcing `ProfileGem/load.sh` twice in your `.bashrc`; this issue only arises if you happened to run `pgem_update`/`pgem_reload` earlier in the shell session - or `load.sh` is sourced more than once)
